version: '2.4'
services:
  config-device-tags:
    build: ./src
    image: 'config-device-tags:1.0.0'
    ports:
      - '55555:80'
    mem_limit: 50mb
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: '3'
      driver: json-file
    volumes:
      - './publish/:/publish/'
      - './cfg-data/:/cfg-data/'
      - './src/html/cfg/:/usr/share/nginx/html/cfg/'
